name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install Backend Dependencies
      working-directory: ./server
      run: npm install
      
    - name: Run Backend Tests
      working-directory: ./server
      run: npm test
      env:
        NODE_ENV: test
        JWT_SECRET: testsecret
        MONGO_URI: mongodb://localhost:27017/testdb

  test-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install Frontend Dependencies
      working-directory: ./client
      run: npm install
      
    - name: Run Frontend Tests
      working-directory: ./client
      run: npm test -- --watchAll=false
      env:
        CI: true